### ISSUE TITLE
How to get battery in advertising data

### ISSUE THREAD

**Issue by matthew-ely** [kkmhogen/KBeaconProDemo_Ios#2]
I am using the KBeaconPro app to check the battery of my hardware beacons and am also working on an app that records the battery history in a database. I have looked through iBeacon protocol and documentation and cannot seem to find where the battery is included in the advertising packet. I am not sure how the app is getting this data.

**Comment by kkmhogen** [comment]
Hi, According to the iBeacon protocol, it is not possible to carry battery power. Our beacon carries the battery level in the scan response, you can refer to the parseAdvPacket function in KBAdvPacketHandler.swift to get it. 
Or you may need to enable the Eddystone TLM protocol to broadcast power.
